# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"logger": "init.ipynb",
         "Period": "init.ipynb",
         "Day": "init.ipynb",
         "always": "init.ipynb",
         "is_weekend": "init.ipynb",
         "is_weekday": "init.ipynb",
         "get_named_weekday": "init.ipynb",
         "specific_weekday": "init.ipynb",
         "year_of": "init.ipynb",
         "is_holiday": "init.ipynb",
         "is_month": "init.ipynb",
         "make_year_specific_date": "init.ipynb",
         "before": "init.ipynb",
         "after": "init.ipynb",
         "NAMED_FUNCTIONS": "init.ipynb",
         "is_known_name": "init.ipynb",
         "Logic": "init.ipynb",
         "DayType": "init.ipynb",
         "IncompleteSchedule": "init.ipynb",
         "Schedule": "init.ipynb"}

modules = ["__init__.py"]

doc_url = "https://talosiot-will.github.io/schedulebuilder/"

git_url = "https://github.com/talosiot-will/schedulebuilder/tree/master/"

def custom_doc_links(name): return None
