# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"logger": "init.ipynb",
         "Period": "init.ipynb",
         "Day": "init.ipynb",
         "Unoccupied": "init.ipynb",
         "AlwaysOn": "init.ipynb",
         "always": "init.ipynb",
         "is_weekend": "init.ipynb",
         "is_weekday": "init.ipynb",
         "is_holiday": "init.ipynb",
         "is_month": "init.ipynb",
         "LOGIC": "init.ipynb",
         "Logic": "init.ipynb",
         "Logics": "init.ipynb",
         "DayType": "init.ipynb",
         "IncompleteSchedule": "init.ipynb",
         "Schedule": "init.ipynb"}

modules = ["__init__.py"]

doc_url = "https://talosiot-will.github.io/schedulebuilder/"

git_url = "https://github.com/talosiot-will/schedulebuilder/tree/master/"

def custom_doc_links(name): return None
